---
title: "linear model"
author: "Zihan Xiong"
date: "2025-12-02"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
library(tidyverse)
library(p8105.datasets)
```

```{r}
data(nyc_airbnb)
nyc_airbnb
```

```{r}
nyc_airbnb=
  nyc_airbnb |>
  mutate(
    stars=review_scores_location/2
  )|>
  rename(
    borough=neighbourhood_group
  )|>
  filter(borough != "Staten Island") |>
  select(price, stars, borough, room_type, neighbourhood
  )

```

do regression!
```{r}
fit=lm(price~stars+borough,data=nyc_airbnb)
fit
```
do some additional cleaning then refit
```{r}
nyc_airbnb |>
  count(borough)

nyc_airbnb=
  nyc_airbnb |>
  mutate(
    borough=fct_infreq(borough),
    room_type=fct_infreq(room_type)
  )
fit=lm(price~stars+borough,data = nyc_airbnb)
fit
```
look at `lm` staff
```{r}
summary(fit) #得到完整回归,解读模型
names(summary(fit)) #了解结构
summary(fit)[["coefficients"]] #系数表,显著性判断,结果整理
summary(fit)[["df"]] #自由度,统计检验,模型复杂度

fitted.values(fit) #预测值,模型诊断
resid(fit) #残差,检查假设寻找异常
```

look at cleaner `lm` stuff
```{r}
fit |>
  broom::tidy() |> #变成干净的数据框格式
  mutate(
    term=str_replace(term,"borough","Borough: ")) |>
      select(term, estimate, p.value) |> #只保留变量名,估计值和p植
      knitr::kable(digits=3)#变成表格,三位小数点

fit |>
  broom::glance()
  #r square的解释力非常弱,需要更多变量, 大于0.75说明比较强
```

```{r}
#残差直方图
#如果偏斜 ➜ 模型预测偏差较大，可能需要变换（如 log(price)）
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  modelr::add_predictions(fit) |> 
  filter(resid < 1000) |> 
  ggplot(aes(x = resid)) + 
  geom_histogram()
```

```{r}
#不同行政区残差分布
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  modelr::add_predictions(fit) |> 
  filter(resid < 1000) |> 
  ggplot(aes(x = borough, y = resid)) + 
  geom_violin()

```
```{r}
#残差vs星级评分
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  modelr::add_predictions(fit) |> 
  filter(resid < 1000) |> 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point()

```
##hypothesis testing
```{r}
fit |>
  broom::tidy()
```
alternative model
```{r}
fit_alt=lm(price~stars+borough+room_type,data = nyc_airbnb)
fit_null=lm(price~stars+borough,data=nyc_airbnb)
```

```{r}
anova(fit_null, fit_alt) |>
  broom::tidy()
```
## interactions vs nested data
```{r}
fit_interactions=
  lm(price~stars*borough+room_type*borough,data=nyc_airbnb)
fit_interactions |>
  broom::tidy()
```
look at brooklyn first
```{r}
nyc_airbnb |>
  filter(borough=="Brooklyn") |>
  lm(price~stars+room_type,data=_) |>
  broom::tidy()

nyc_airbnb |>
  filter(borough=="Queens") |>
  lm(price~stars+room_type,data=_) |>
  broom::tidy()

nyc_airbnb |>
  filter(borough=="Manhattan") |>
  lm(price~stars+room_type,data=_) |>
  broom::tidy()

nyc_airbnb |>
  filter(borough=="Bronx") |>
  lm(price~stars+room_type,data=_) |>
  broom::tidy()
```
write a short function
```{r}
lm_airbnb=function(df) {
  
  lm(price~stars+room_type, data=df)
} 
nyc_airbnb |>
  filter(borough=="Queens") |>
  lm_airbnb() |>
  broom::tidy()
```
create a list of dataframes, and iterate to fit the model each time.

```{r}

```










